### ISSUE TITLE
DX12 black screen

### ISSUE THREAD

**Issue by YotPhiligan** [SiliconStudio/xenko#443]
When try to launch project with DX12 profile scene not rendered as expected always black screen.
It is works fine with Vulkan profile and default.

My spec:
Win10 x64, AMD Radeon R9 280X

**Comment by xen2** [comment]
Not sure if related, but we've already fixed some texture uploading issues (esp. affecting AMD) in our master branch.
I have just backported them in 1.7, so it should be available in next 1.7.8+ releases.

In case you want to early-test it, you can unzip the attached `SiliconStudio.Xenko.Graphics.dll` in your `%SiliconStudioXenkoDir%\GamePackages\Xenko.1.6.7-beta\Bin\Windows-Direct3D12` folder.

[SiliconStudio.Xenko.Graphics.zip](https://github.com/SiliconStudio/xenko/files/392853/SiliconStudio.Xenko.Graphics.zip)

**Comment by YotPhiligan** [comment]
After 1.7.9 update still not working

DX12 error log:
`[Game]: Error: Unexpected exception. SharpDX.SharpDXException: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: ╨н╨║╨╖╨╡╨╝╨┐╨╗╤П╤А ╤Г╤Б╤В╤А╨╛╨╣╤Б╤В╨▓╨░ GPU ╨┐╤А╨╕╨╛╤Б╤В╨░╨╜╨╛╨▓╨╗╨╡╨╜. ╨Ф╨╗╤П ╨╛╨┐╤А╨╡╨┤╨╡╨╗╨╡╨╜╨╕╤П ╤Б╨╛╨╛╤В╨▓╨╡╤В╤Б╤В╨▓╤Г╤О╤Й╨╡╨│╨╛ ╨┤╨╡╨╣╤Б╤В╨▓╨╕╤П ╨╕╤Б╨┐╨╛╨╗╤М╨╖╤Г╨╣╤В╨╡ GetDeviceRemovedReason.

   ╨▓ SharpDX.Result.CheckError()
   ╨▓ SharpDX.Direct3D12.Device.CreateDescriptorHeap(DescriptorHeapDescription descriptorHeapDescRef, Guid riid)
   ╨▓ SiliconStudio.Xenko.Graphics.GraphicsDevice.DescriptorAllocator.Allocate(Int32 count)
   ╨▓ SiliconStudio.Xenko.Graphics.Texture.GetRenderTargetView(ViewType viewType, Int32 arrayOrDepthSlice, Int32 mipIndex)
   ╨▓ SiliconStudio.Xenko.Graphics.Texture.InitializeFromImpl(DataBox[] dataBoxes)
   ╨▓ SiliconStudio.Xenko.Graphics.Texture.InitializeFrom(Texture parentTexture, TextureDescription description, TextureViewDescription viewDescription, DataBox[] textureDatas)
   ╨▓ SiliconStudio.Xenko.Graphics.Texture.InitializeFrom(Resource texture, Boolean isSrgb)
   ╨▓ SiliconStudio.Xenko.Graphics.SwapChainGraphicsPresenter..ctor(GraphicsDevice device, PresentationParameters presentationParameters)
   ╨▓ SiliconStudio.Xenko.Games.GamePlatform.CreateDevice(GraphicsDeviceInformation deviceInformation)
   ╨▓ SiliconStudio.Xenko.Games.GamePlatform.ChangeOrCreateDevice(GraphicsDevice currentDevice, GraphicsDeviceInformation deviceInformation)
   ╨▓ SiliconStudio.Xenko.Games.GraphicsDeviceManager.CreateDevice(GraphicsDeviceInformation newInfo)
   ╨▓ SiliconStudio.Xenko.Games.GraphicsDeviceManager.ChangeOrCreateDevice(Boolean forceCreate)
   ╨▓ SiliconStudio.Xenko.Games.GraphicsDeviceManager.SiliconStudio.Xenko.Games.IGraphicsDeviceManager.CreateDevice()
   ╨▓ SiliconStudio.Xenko.Games.GameBase.InitializeBeforeRun()
SharpDX.SharpDXException: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: ╨н╨║╨╖╨╡╨╝╨┐╨╗╤П╤А ╤Г╤Б╤В╤А╨╛╨╣╤Б╤В╨▓╨░ GPU ╨┐╤А╨╕╨╛╤Б╤В╨░╨╜╨╛╨▓╨╗╨╡╨╜. ╨Ф╨╗╤П ╨╛╨┐╤А╨╡╨┤╨╡╨╗╨╡╨╜╨╕╤П ╤Б╨╛╨╛╤В╨▓╨╡╤В╤Б╤В╨▓╤Г╤О╤Й╨╡╨│╨╛ ╨┤╨╡╨╣╤Б╤В╨▓╨╕╤П ╨╕╤Б╨┐╨╛╨╗╤М╨╖╤Г╨╣╤В╨╡ GetDeviceRemovedReason.

   ╨▓ SharpDX.Result.CheckError()
   ╨▓ SharpDX.Direct3D12.Device.CreateDescriptorHeap(DescriptorHeapDescription descriptorHeapDescRef, Guid riid)
   ╨▓ SiliconStudio.Xenko.Graphics.GraphicsDevice.DescriptorAllocator.Allocate(Int32 count)
   ╨▓ SiliconStudio.Xenko.Graphics.Texture.GetRenderTargetView(ViewType viewType, Int32 arrayOrDepthSlice, Int32 mipIndex)
   ╨▓ SiliconStudio.Xenko.Graphics.Texture.InitializeFromImpl(DataBox[] dataBoxes)
   ╨▓ SiliconStudio.Xenko.Graphics.Texture.InitializeFrom(Texture parentTexture, TextureDescription description, TextureViewDescription viewDescription, DataBox[] textureDatas)
   ╨▓ SiliconStudio.Xenko.Graphics.Texture.InitializeFrom(Resource texture, Boolean isSrgb)
   ╨▓ SiliconStudio.Xenko.Graphics.SwapChainGraphicsPresenter..ctor(GraphicsDevice device, PresentationParameters presentationParameters)
   ╨▓ SiliconStudio.Xenko.Games.GamePlatform.CreateDevice(GraphicsDeviceInformation deviceInformation)
   ╨▓ SiliconStudio.Xenko.Games.GamePlatform.ChangeOrCreateDevice(GraphicsDevice currentDevice, GraphicsDeviceInformation deviceInformation)
   ╨▓ SiliconStudio.Xenko.Games.GraphicsDeviceManager.CreateDevice(GraphicsDeviceInformation newInfo)
   ╨▓ SiliconStudio.Xenko.Games.GraphicsDeviceManager.ChangeOrCreateDevice(Boolean forceCreate)
   ╨▓ SiliconStudio.Xenko.Games.GraphicsDeviceManager.SiliconStudio.Xenko.Games.IGraphicsDeviceManager.CreateDevice()
   ╨▓ SiliconStudio.Xenko.Games.GameBase.InitializeBeforeRun()

Необработанное исключение: SharpDX.SharpDXException: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Экземпляр устройства GPU приостановлен. Для определения соответствующего действия используйте GetDeviceRemovedReason.

   в SharpDX.Result.CheckError()
   в SharpDX.Direct3D12.Device.CreateDescriptorHeap(DescriptorHeapDescription descriptorHeapDescRef, Guid riid)
   в SiliconStudio.Xenko.Graphics.GraphicsDevice.DescriptorAllocator.Allocate(Int32 count)
   в SiliconStudio.Xenko.Graphics.Texture.GetRenderTargetView(ViewType viewType, Int32 arrayOrDepthSlice, Int32 mipIndex)
   в SiliconStudio.Xenko.Graphics.Texture.InitializeFromImpl(DataBox[] dataBoxes)
   в SiliconStudio.Xenko.Graphics.Texture.InitializeFrom(Texture parentTexture, TextureDescription description, TextureViewDescription viewDescription, DataBox[] textureDatas)
   в SiliconStudio.Xenko.Graphics.Texture.InitializeFrom(Resource texture, Boolean isSrgb)
   в SiliconStudio.Xenko.Graphics.SwapChainGraphicsPresenter..ctor(GraphicsDevice device, PresentationParameters presentationParameters)
   в SiliconStudio.Xenko.Games.GamePlatform.CreateDevice(GraphicsDeviceInformation deviceInformation)
   в SiliconStudio.Xenko.Games.GamePlatform.ChangeOrCreateDevice(GraphicsDevice currentDevice, GraphicsDeviceInformation deviceInformation)
   в SiliconStudio.Xenko.Games.GraphicsDeviceManager.CreateDevice(GraphicsDeviceInformation newInfo)
   в SiliconStudio.Xenko.Games.GraphicsDeviceManager.ChangeOrCreateDevice(Boolean forceCreate)
   в SiliconStudio.Xenko.Games.GraphicsDeviceManager.SiliconStudio.Xenko.Games.IGraphicsDeviceManager.CreateDevice()
   в SiliconStudio.Xenko.Games.GameBase.InitializeBeforeRun()
   в SiliconStudio.Xenko.Games.GamePlatform.OnInitCallback()
   в SiliconStudio.Xenko.Games.GameWindowWinforms.Run()
   в SiliconStudio.Xenko.Games.GamePlatform.Run(GameContext gameContext)
   в SiliconStudio.Xenko.Games.GameBase.Run(GameContext gameContext)
   в VoidMania.VoidManiaApp.Main(String[] args) в D:\Xenko\Projects\VoidMania\VoidMania\VoidMania.Windows\VoidManiaApp.cs:строка 11`

And now also not working if you have chosen a Vulkan dx11 and default
